apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: processing-rabbit
  namespace: infra
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "processing"
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
      default_user = guest
      default_pass = guest
