apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-merger-deployment
  namespace: processing
  labels:
    app: merger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-merger
  template:
    metadata:
      labels:
        app: echo-merger
    spec:
      containers:
        - name: echo-merger
          image: processing/echo-merger:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: CPL_DEBUG
              value: "ON"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/resources/gcp.json"
            - name: CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE
              value: "YES"
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          hostPath:
            path: /data
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8093
#            initialDelaySeconds: 60
#            periodSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8093
#            initialDelaySeconds: 60
#            periodSeconds: 5
